# syntax=docker/dockerfile:1

FROM golang:1.19

# Set destination for COPY
WORKDIR /app

# Get source code and go file
COPY go.mod go.sum server.go ./

# Get dependencies
RUN go mod download

# Expose server port
EXPOSE 8080

# Build server binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server

# Run the server binary
ENTRYPOINT [ "/app/server" ]
