apiVersion: v1
kind: Service
metadata:
  name: cowboy
spec:
  selector:
    app: cowboy
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowboy
spec:
  selector:
    matchLabels:
      app: cowboy
  replicas: 5
  template:
    metadata:
      labels:
        app: cowboy
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: cowboy-config
      containers:
      - name: cowboy
        image: cowboy:1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config-volume
            mountPath: /config
        ports:
        - containerPort: 8080
